### ISSUE TITLE
ValidationException: processor not found (ErrorCode: 1, ResponseCode: )

### ISSUE THREAD

**Issue by onlyxwebdesign** [vitorccs/maxipago-php-sdk#6]
Olá, utilizei o seu código e estou recebendo o erro abaixo, sabe o que pode ser? Será que falta alguma autorização por parte da maxipago ainda?

ValidationException: processor not found (ErrorCode: 1, ResponseCode: )

[]'s

**Comment by vitorccs** [comment]
@onlyxwebdesign 

É bem provável que sim! 

Mesmo em ambiente de homologação, você precisa pedir a Maxipago para configurar a forma de pagamento desejada (boleto / pix / cartão). 

Em Boleto e PIX, quando omito (não informo) o Processor , ele assume o padrão e funciona bem. No cartão, notei que eu tinha que especificar REDE (C´ódigo 2) para funcionar.

Tentar usar o SIMULATOR (Código 1) no ambiente de homologação. Depois, tenta omitir (não especificar o processor), para ver se ele encontra um processor padrão.

**Comment by vitorccs** [comment]
Fechando por inatividade
